// flow-typed signature: 8060b0942792e9a20012d8ad63bdbf7c
// flow-typed version: <<STUB>>/react-document-meta_v^2.1.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-document-meta'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-document-meta' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-document-meta/dist/__tests__/basic.test' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/__tests__/dom.basic.test' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/__tests__/dom.nested.test' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/__tests__/test-utils' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/__tests__/testdom' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/dom' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/index' {
  declare module.exports: any;
}

declare module 'react-document-meta/dist/utils' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/__tests__/basic.test' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/__tests__/dom.basic.test' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/__tests__/dom.nested.test' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/__tests__/test-utils' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/__tests__/testdom' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/dom' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/index' {
  declare module.exports: any;
}

declare module 'react-document-meta/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-document-meta/dist/__tests__/basic.test.js' {
  declare module.exports: $Exports<'react-document-meta/dist/__tests__/basic.test'>;
}
declare module 'react-document-meta/dist/__tests__/dom.basic.test.js' {
  declare module.exports: $Exports<'react-document-meta/dist/__tests__/dom.basic.test'>;
}
declare module 'react-document-meta/dist/__tests__/dom.nested.test.js' {
  declare module.exports: $Exports<'react-document-meta/dist/__tests__/dom.nested.test'>;
}
declare module 'react-document-meta/dist/__tests__/test-utils.js' {
  declare module.exports: $Exports<'react-document-meta/dist/__tests__/test-utils'>;
}
declare module 'react-document-meta/dist/__tests__/testdom.js' {
  declare module.exports: $Exports<'react-document-meta/dist/__tests__/testdom'>;
}
declare module 'react-document-meta/dist/dom.js' {
  declare module.exports: $Exports<'react-document-meta/dist/dom'>;
}
declare module 'react-document-meta/dist/index.js' {
  declare module.exports: $Exports<'react-document-meta/dist/index'>;
}
declare module 'react-document-meta/dist/utils.js' {
  declare module.exports: $Exports<'react-document-meta/dist/utils'>;
}
declare module 'react-document-meta/lib/__tests__/basic.test.js' {
  declare module.exports: $Exports<'react-document-meta/lib/__tests__/basic.test'>;
}
declare module 'react-document-meta/lib/__tests__/dom.basic.test.js' {
  declare module.exports: $Exports<'react-document-meta/lib/__tests__/dom.basic.test'>;
}
declare module 'react-document-meta/lib/__tests__/dom.nested.test.js' {
  declare module.exports: $Exports<'react-document-meta/lib/__tests__/dom.nested.test'>;
}
declare module 'react-document-meta/lib/__tests__/test-utils.js' {
  declare module.exports: $Exports<'react-document-meta/lib/__tests__/test-utils'>;
}
declare module 'react-document-meta/lib/__tests__/testdom.js' {
  declare module.exports: $Exports<'react-document-meta/lib/__tests__/testdom'>;
}
declare module 'react-document-meta/lib/dom.js' {
  declare module.exports: $Exports<'react-document-meta/lib/dom'>;
}
declare module 'react-document-meta/lib/index.js' {
  declare module.exports: $Exports<'react-document-meta/lib/index'>;
}
declare module 'react-document-meta/lib/utils.js' {
  declare module.exports: $Exports<'react-document-meta/lib/utils'>;
}
